# Generated by Django 6.0.7 on 2026-07-28 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Avtomobil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modeli', models.CharField(max_length=100)),
                ('markasi', models.CharField(max_length=100)),
                ('narxi', models.DecimalField(decimal_places=2, max_digits=10)),
                ('ishlab_chiqarilgan_yili', models.IntegerField()),
                ('yurgan_masofasi', models.IntegerField()),
                ('izohi', models.TextField(blank=True)),
                ('yaratilgan_vaqti', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
