# Generated by Django 6.0.7 on 2026-08-03 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_ishlabchiqaruvchi_avtomobil_ishlab_chiqaruvchi'),
    ]

    operations = [
        migrations.AddField(
            model_name='avtomobil',
            name='kod',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='avtomobil',
            name='oxirgi_tahrirlagan',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='avtomobil',
            name='yaratuvchi',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
